spring:
  datasource:
    url: jdbc:mysql://localhost:3306/merry_meal_1
    username: root
    password: harris542002##
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 273515586173-6eih2pbj7dnm8p34e3ugfe1k49to3n7m.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 721789279508498
            client-secret: 6bfdb07c8af40db3db669470b595d37f
            scope:
                - email
                - public_profile
        provider: 
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,email,first_name,middle_name,last_name,name,verified,picture.width(250).height(250)

logging:
  level:
    ROOT: DEBUG
       
app:
  auth:
    tokenSecret: 0555ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect